### ISSUE TITLE
getItem Error

### ISSUE THREAD

**Issue by ESSutherland** [oscar0812/pokeapi-v2-java#1]
Not sure if you are still supporting this, but it was the only Java wrapper for the API I could find that worked. When I try to get certain items by name or id, it returns an error like this: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 10003 path $.held_by_pokemon[0].pokemon.

**Comment by oscar0812** [comment]
Hey! It has been a while since I have maintained this API wrapper, but I am
getting it back on its feet! Can you describe the error in more detail?

**Comment by oscar0812** [comment]
Also, I've updated most of the code recently. I believe I fixed (created?) some bugs. Give it a go with the new code :)

**Comment by ESSutherland** [comment]
The problem I have is when I call client.getItemByName(). for example when I call client.getItemByName("moon-stone"); I get the error: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 10503 path $.held_by_pokemon[0].pokemon. But if I use client.getItemByName("thunder-stone"); it works fine.

**Comment by oscar0812** [comment]
I tested both Client.getItemByName("moon-stone"); and Client.getItemByName("thunder-stone"); and they work fine.

**Comment by oscar0812** [comment]
I'm going to close this since it's fixed. Feel free to reopen if you reencounter this issue.
